# Generated by Django 6.1.1 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('category', models.CharField(max_length=80)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
            ],
            options={'ordering': ['date', 'id']},
        ),
    ]
